---
- name: (Handler) Restart rootless user manager
  ansible.builtin.systemd:
    name: user@{{ docker_rootless_uid }}.service
    state: restarted
    daemon_reload: true
    scope: system

- name: (Handler) Restart rootless docker.service
  become: true
  become_user: "{{ docker_rootless_user }}"
  become_flags: --login
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
    daemon_reload: true
    scope: user

- name: (Handler) Restart system docker.service
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
    daemon_reload: true
    scope: system
