---
# Uninstall Docker packages

- name: Uninstall and Purge Docker packages
  ansible.builtin.apt:
    name: "{{ docker_pkgs }}"
    state: absent
    purge: true
    autoremove: true
    allow_change_held_packages: true

- name: Remove Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    state: absent
